apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: discord-ex
build:
  artifacts:
    - image: bull
      context: ./
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - ./k8s
