apiVersion: apps/v1
kind: Deployment
metadata:
  name: bull-deployment
  labels:
    app: bull
spec:
  selector:
    matchLabels:
      app: bull
  template:
    metadata:
      labels:
        app: bull
    spec:
      containers:
        - name: bull
          image: bull
          envFrom:
            - secretRef:
                name: secrets
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
